title: Applications of Universal Dependencies

description: > 
  Applications of Universal Dependencies, co-located with SLTC-2024

header_pages:
  - program.md

remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%-d %B %Y"
